### ISSUE TITLE
genny supporting dart ffi

### ISSUE THREAD

**Issue by kobi2187** [treeform/pixie-python#15]
Hi treeform, 
very nice lib (looking at the python output), 
I have recently discovered Flutter over dart language, 
they create a nice vibrant UI experience. 
BUT:

its ffi lib is just so ugly, *shudders*!
it's ffi interop is very verbose and looks annoying to get done,
at the same time, devs seem to flock to this (relatively) new platform 
but not many want to get hands dirty in C code, so Nim to the rescue right?

Can genny also support the dart programming language? it's just generating a lot of ugly boilerplate code.

I think it's a chance to get more people to use Nim, and thereby building more libs and contributing to it, which was one of your purposes with genny.

Aside from that, I personally want to leverage Nim libraries that i and others have written, and use dart and flutter mainly for the GUI story (though in terms of features, dart looks to be a decent language. unfortunately for dart, in terms of syntax - verbose like java and I think no templates, but this is just first impressions.)

**Comment by treeform** [comment]
Hey, I think you meant to file this inside genny's repo. This is the pixie-python repo (which is generated by genny).

Genny is meant to take a nim library like pixie and expose it to other languages. So if some one does write a cool Nim lib it can be used beyond nim. Genny does `nim -> *`.

Flitter is a library written for Dart. Genny does not do `dart -> nim` or `anything else -> nim` because it doest `nim -> some thing else`. I don't think genny will be able to help you with a flutter dart library its just not meant for this. Sorry.

In theory genny could support Dart, but again it will be used to make libraries like pixie-for-dart. Not flutter-for-nim.

I'll close this issue, but feel free to reopen if it does not make sense.

**Comment by kobi2187** [comment]
Thank you for being so polite. I just accidentally posted here. I did mean nim -> dart, in order to use good nim libs in the final application.
