### ISSUE TITLE
Unable to load jpg on Linux

### ISSUE THREAD

**Issue by EdMUK** [treeform/pixie-python#19]
Installed pixie-python via pip, however when I try to load a JPG I get the following exception.
```
Exception has occurred: PixieError
Decoding JPG requires -d:pixieUseStb
```
I guess pixie is using std image library under the hood and the package did not get compiled with the correct options to support this?

**Comment by guzba** [comment]
Thanks for pointing this out, we can and will address this.

**Comment by guzba** [comment]
Quick update here. Unfortunately it turns out compiling the Pixie dynamic lib with the JPG code included results in Python not able to open the DLL. There must be some dependency of some kind that isn't being met or something.

We intend do write our own JPG reader / writer but have not gotten to it yet, hence the dependency. Unless we find a workaround, pixie-python will continue to not have JPG until we can do that.

**Comment by guzba** [comment]
Update here. We've now got a pure Nim jpeg decoder which appears to be working well via dll/dylib/so. PR is https://github.com/treeform/pixie-python/pull/21. Will close this once we've merged that and put out a release on pip.
